const presetConfig = [
  {
    index: 0,
    text: `The cerebral cortex is the intricate fabric of interconnected neural cells covering the cerebral hemispheres; the body’s ultimate control and information-processing center. It is divided into four regions called lobes: the frontal lobe, parietal lobe, temporal lobe, and occipital lobe. It is located in both the right and left hemispheres. The frontal lobes are involved in speaking, motor movements, judgement, and decision making. The parietal lobes receive and processes sensory input for touch and body position. The temporal lobes receive auditory information, primarily from the opposite ear. The occipital lobes receive visual information, primarily from the opposite visual field. The motor cortex controls voluntary movements. The somatosensory cortex registers information from the skin senses and body movements. The auditory cortex receives information from the ears. The visual cortex receives information from the eyes. The most of the brain’s cortex which integrates information involved in learning, remembering, thinking, and other higher-level functions. Attention is shifted, and planning occurs. The association areas are not specifically devoted or sensory cortex functions.
  If you opened a human skull, exposing the brain, you would see a wrinkled organ, shaped somewhat like the meat of an oversized walnut. Without these wrinkles, a flattened cerebral cortex would require triple the area-roughly that of a large pizza. The brain's left and right hemispheres are filled mainly with axons connecting the cortex to the brain's other regions. The cerebral cortex-that thin surface layer-contains some 20 to 23 billion of the brain's nerve cells and 300 trillion synaptic connections (de Courten-Myers, 2005). Being human takes a lot of  nerve. Each hemisphere's cortex is subdivided into four lobes, separated by prominent fissures, or folds. Starting at the front of your brain and moving over the top, there are the frontal lobes (behind your forehead), the parietal lobes (at the top and to the rear), and the occipital lobes (at the back of your head). Reversing direction and moving forward, just above your ears, you find the temporal lobes. Each of the four lobes carries out many functions, and many functions require the interplay of several lobes.
  The two hemispheres of the cerebral cortex are part of the forebrain (Figure 1), which is the largest part of the brain. The forebrain contains the cerebral cortex and a number of other structures that lie beneath the cortex (called subcortical structures): thalamus, hypothalamus, pituitary gland, and the limbic system (collection of structures). The cerebral cortex, which is the outer surface of the brain, is associated with higher level processes such as consciousness, thought, emotion, reasoning, language, and memory. Each cerebral hemisphere can be subdivided into four lobes, each associated with different functions. The four lobes of the brain are the frontal, parietal, temporal, and occipital lobes (Figure 2). The frontal lobe is located in the forward part of the brain, extending back to a fissure known as the central sulcus. The frontal lobe is involved in reasoning, motor control, emotion, and language. It contains the motor cortex, which is involved in planning and coordinating movement; the prefrontal cortex, which is responsible for higher-level cognitive functioning; and Broca’s area, which is essential for language production.
  Each cerebral hemisphere can be subdivided into four lobes, each associated with different functions. The frontal lobes are located at the front of the brain, behind the forehead (Figure 4). Their main functions are associated with higher cognitive functions, including problem-solving, decision-making, attention, intelligence, and voluntary behaviors. The frontal lobes contain the motor cortex, which is responsible for planning and coordinating movements. It also contains the prefrontal cortex, which is responsible for initiating higher-lever cognitive functioning, and Broca’s Area, which is essential for language production. The temporal lobes are located on both sides of the brain, near the temples of the head, hence the name temporal lobes (Figure 5). The main functions of these lobes include understanding, language, memory acquisition, face recognition, object recognition, perception, and processing auditory information. There is a temporal lobe in both the left and right hemispheres. The left temporal lobe, which is usually the most dominant in people is associated with language, learning, memorising, forming words, and remembering verbal information. The left lobe also contains an important language centre known as Wernicke’s area, which is essential for language development. The right temporal lobe is usually associated with learning and memorising non-verbal information and determining facial expressions. The parietal lobe is located at the top of the brain, between the frontal and occipital lobes, above the temporal lobes (Figure 6). The parietal lobe is essential for integrating information from the body’s senses in order to allow us to build a coherent picture of the world around us. These lobes allow us to have a perception of our bodies through somatosensory information (e.g. through touch, pressure, and temperature). It can also help with visuospatial processing, reading, and number representations (mathematics). The parietal lobes also contain the somatosensory cortex, which receives and processes sensory information, integrating this into a representational map of the body. This means it can pinpoint the exact area of the body where sensation is felt, as well as being able to perceive the weight of objects, shape, and texture. The occipital lobes are located at the back of the brain behind the temporal and parietal lobes and below the occipital bone of the skull (Figure 7). The occipital lobes receive sensory information from the retinas of the eyes which is then encoded into different visual data. Some of the functions of the occipital lobes include being able to assess size, depth, and distance, determine colour information, object and facial recognition, and mapping the visual world. The occipital lobes also contain the primary visual cortex which receives sensory information from the retinas, transmitting this information relating to location, spatial data, motion, and the colours of objects in the field of vision.
  `,
  },
  {
    index: 1,
    text: `Intermolecular Forces London Forces: •All molecules have London Forces •Weakest of the intermolecular forces •Caused by motion of electrons creating a temporary dipole in non-polar molecules •The opposite charges attract each other creating an attraction between the molecules •The extent of the London forces affects how the molecules clump together to condense or freeze affects the state
    Intermolecular Forces London Forces: 
    Consider a F 2 molecule: •The electrons that are not part of the bond are not static, they continue to move around •• F •• •• •• •• F •• •At any point in time more of the electrons could be on one side of the molecule than the other causing a temporary dipole •••• •• •• δ+ F •• F •• δ– •These temporary dipoles attract each other
    Intermolecular Forces Dipole-Dipole Forces: •Polar molecules have dipole-dipole attractions •Medium strength intermolecular forces –stronger than London forces •Uneven distribution of charge in the molecule caused by electronegativity and molecule shape causes a permanent dipole •The opposite charges attract each other creating an attraction between the molecules •The extent of these forces affects how the molecules clump together to condense or freeze affects the state
    Intermolecular Forces Hydrogen Bonding: •Special case of Dipole-dipole forces •Strongest of the intermolecular forces •Only occurs when you have H bonded N, O, or F •The other atom (N, O, or F) is very electronegative and pulls electrons towards itself causing the H to become δ+ and the other atom to become δ–. In the water molecule shown in the diagram the oxygen pulls electrons towards itself making the oxygen slightly negative, and the hydrogen atoms slightly positive
    Intermolecular Forces Hydrogen Bonding: •Explains why water is liquid at room temperature when other molecules with much larger molar masses such as CO 2 are gases at room temperature. •The molecules attract and form a network of water molecules which causes surface tension.
    
    
    `,
  },
];

export default presetConfig;
